name: deploy_frontend

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Use OIDC login instead of service principal login
    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Optional for OIDC, you can leave this empty
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Optional for OIDC, you can leave this empty
        federated-credentials: true  # This enables OIDC-based login

    # Upload files to Blob Storage
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name myresumestorage --auth-mode key -d '$web' -s frontend/

    # Purge the CDN endpoint
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "alexdelievcloudresume" --name "alexdelievcloudresume" --resource-group "azureresume-rg"

    # Logout from Azure
    - name: logout
      run: |
            az logout
      if: always()
